### ISSUE TITLE
Name is too generic

### ISSUE THREAD

**Issue by bragefuglseth** [fkinoshita/Vibrant#1]
Hi there! The name «Gradients» is on point for what the app does, but it’s also very generic. This makes it hard to remember, discuss and promote. It’s easier to change this early on, which is why I’m opening this issue now.

**Comment by fkinoshita** [comment]
I completely agree! If you have any suggestion feel free to send them :)

**Comment by bragefuglseth** [comment]
Some initial suggestions:
- Gradual
- Embellishment
- Chromatic
- Vibrant
- Pigments

**Comment by fkinoshita** [comment]
Chromatic is already used by another app, I think Vibrant is a good choice!
